#PBS -N STARindex
#PBS -e STARindex.error
#PBS -o STARindex.out
#PBS -l nodes=1:ppn=1
#PBS -l  mem=120000MB
#PBS -l vmem=120000MB
#PBS -l pmem=120000MB
#PBS -l walltime=400:00:00
#PBS -q cmb
#!/bin/bash
cd "$PBS_O_WORKDIR"

mkdir STAR_mg38_index
cd STAR_mg38_index

STAR --runThreadN 8 --runMode genomeGenerate \
     --genomeFastaFiles ../GRCm38.p5.genome.fa \
     --genomeDir $PWD \
     --sjdbGTFfile ../gencode.vM16.annotation.gtf \
