#PBS -N STARindex
#PBS -e STARindex.error
#PBS -o STARindex.out
#PBS -l nodes=1:ppn=1
#PBS -l  mem=120000MB
#PBS -l vmem=120000MB
#PBS -l pmem=120000MB
#PBS -l walltime=400:00:00
#PBS -q cmb
#!/bin/bash
cd "$PBS_O_WORKDIR"

mkdir STAR_hg38_index
cd STAR_hg38_index

STAR --runThreadN 1 --runMode genomeGenerate \
     --genomeFastaFiles ../GRCh38.p10.genome.fa \
     --genomeDir $PWD \
     --sjdbGTF \
     --genomeDir $PWD \
     --sjdbGTFfile ../gencode.v27.annotation.gtf
